name: Secret Demo Workflow

on:
  push:
      paths: 
        - "MySecret.yml"
        - 'scripts/mysecret.sh'
      branches:
        - main
jobs:
       secret-demo:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: Access secret
            run: echo "Secret is $MY_SECRET"
            env:
              MY_SECRET: ${{ secrets.MY_SECRET }}
